export const ECO_ROUTING_TEXT = {
  status: {
    selectPoints: 'Select start and destination',
    roadReady: 'Road Verified',
    estimated: 'Estimated mode',
    degraded: 'AQI data degraded',
    avoidFiltered: 'Avoid areas filter all routes',
    avoidAddMode: 'Click map to place avoid area',
  },
  buttons: {
    optimize: 'Optimize Eco Route',
    optimizing: 'Optimizing...',
    demo: 'Demo Analysis',
  },
  labels: {
    fastest: 'Fastest',
    balanced: 'Balanced',
    cleanest: 'Cleanest',
    fastestEta: 'Fastest ETA',
    lowestAqi: 'Lowest AQI',
    lowestCo2: 'Lowest CO2',
    routeVerified: 'Road Verified',
    routeEstimated: 'Estimated',
    ecoScore: 'Eco Score',
    aqiExposure: 'AQI Exposure',
    co2: 'CO2',
    avoidAreas: 'Avoid areas',
    avoidEnabled: 'Avoid enabled',
    avoidDisabled: 'Avoid disabled',
  },
  map: {
    focusRoute: 'Route',
    focusAll: 'All',
    focusPoints: 'A-B',
    lightMode: 'Light',
    darkMode: 'Dark',
    focusRouteTitle: 'Focus selected route',
    focusAllTitle: 'Fit all alternatives',
    focusPointsTitle: 'Fit start and destination',
    toggleThemeTitle: 'Toggle map theme',
    fullscreenEnter: 'Fullscreen',
    fullscreenExit: 'Exit fullscreen',
    fullscreenTitle: 'Toggle fullscreen map',
    dragHint: 'Drag A/B and avoid points',
    scaleTitle: 'Map scale',
    compassNorth: 'N',
  },
  avoid: {
    addArea: 'Add Avoid Area',
    addingArea: 'Click On Map',
    clearAll: 'Clear All',
    empty: 'No avoid areas set',
    radius: 'Radius',
    remove: 'Remove',
  },
  tooltips: {
    invalidPoints: 'Select both start and destination first',
  },
} as const;
